# Generated by Django 4.2.4 on 2025-04-13 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre y apellido')),
                ('dni', models.CharField(verbose_name='DNI')),
                ('phone', models.CharField(verbose_name='Tel')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('model_pk', models.IntegerField(default=0)),
                ('msg', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Estado Parcelario', 'Estado Parcelario'), ('Mensura', 'Mensura'), ('Amojonamiento', 'Amojonamiento'), ('Relevamiento', 'Relevamiento'), ('Legajo Parcelario', 'Legajo Parcelario')], max_length=30, verbose_name='Proyecto')),
                ('mens', models.CharField(choices=[('PH', 'PH'), ('Usucapion', 'Usucapion'), ('Division', 'Division'), ('Anexion/Division', 'Anexion/Division'), ('Unificacion', 'Unificacion')], max_length=30, verbose_name='Mensura')),
                ('titular_name', models.CharField(max_length=30, verbose_name='Nombre y apellido')),
                ('titular_dni', models.IntegerField(verbose_name='DNI')),
                ('titular_phone', models.IntegerField(verbose_name='Telefono')),
                ('partido', models.CharField(blank=True, max_length=30, verbose_name='Partido')),
                ('partida', models.CharField(blank=True, max_length=30, verbose_name='Partida')),
                ('circuns', models.CharField(blank=True, max_length=30, verbose_name='Circunscripcion')),
                ('seccion', models.CharField(blank=True, max_length=30, verbose_name='Seccion')),
                ('chacra_num', models.CharField(blank=True, max_length=10, verbose_name='Numero')),
                ('chacra_letra', models.CharField(blank=True, max_length=10, verbose_name='Letra')),
                ('quinta_num', models.CharField(blank=True, max_length=10, verbose_name='Numero')),
                ('quinta_letra', models.CharField(blank=True, max_length=10, verbose_name='Letra')),
                ('fraccion_num', models.CharField(blank=True, max_length=10, verbose_name='Numero')),
                ('fraccion_letra', models.CharField(blank=True, max_length=10, verbose_name='Letra')),
                ('inscription_type', models.CharField(choices=[('Folio', 'Folio'), ('Matricula', 'Matricula')], default='', max_length=30, null=True, verbose_name='Parcela')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Presupuesto')),
                ('adv', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Anticipo')),
                ('gasto', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Gastos')),
                ('procedure', models.IntegerField(null=True, verbose_name='N° Tramite')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='media/files')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project')),
            ],
        ),
    ]
