# Generated by Django 4.2.4 on 2023-08-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='noment_circuns',
        ),
        migrations.RemoveField(
            model_name='project',
            name='noment_partido',
        ),
        migrations.RemoveField(
            model_name='project',
            name='noment_seccion',
        ),
        migrations.RemoveField(
            model_name='project',
            name='partida_manzana',
        ),
        migrations.RemoveField(
            model_name='project',
            name='partida_parcela',
        ),
        migrations.RemoveField(
            model_name='project',
            name='partida_quinta',
        ),
        migrations.AddField(
            model_name='project',
            name='chacra_letra',
            field=models.CharField(max_length=10, null=True, verbose_name='Quinta'),
        ),
        migrations.AddField(
            model_name='project',
            name='chacra_num',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='project',
            name='circuns',
            field=models.CharField(max_length=30, null=True, verbose_name='Circunscripcion'),
        ),
        migrations.AddField(
            model_name='project',
            name='fraccion_letra',
            field=models.CharField(max_length=10, null=True, verbose_name='Letra'),
        ),
        migrations.AddField(
            model_name='project',
            name='fraccion_num',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='project',
            name='inscription_type',
            field=models.CharField(choices=[('Folio', 'Folio'), ('Matricula', 'Matricula')], max_length=30, null=True, verbose_name='Parcela'),
        ),
        migrations.AddField(
            model_name='project',
            name='manzana_letra',
            field=models.CharField(max_length=10, null=True, verbose_name='Letra'),
        ),
        migrations.AddField(
            model_name='project',
            name='manzana_num',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='project',
            name='parcela_letra',
            field=models.CharField(max_length=10, null=True, verbose_name='Letra'),
        ),
        migrations.AddField(
            model_name='project',
            name='parcela_num',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='project',
            name='partida',
            field=models.CharField(max_length=30, null=True, verbose_name='Partido'),
        ),
        migrations.AddField(
            model_name='project',
            name='partido',
            field=models.CharField(max_length=30, null=True, verbose_name='Partido'),
        ),
        migrations.AddField(
            model_name='project',
            name='quinta_letra',
            field=models.CharField(max_length=10, null=True, verbose_name='Letra'),
        ),
        migrations.AddField(
            model_name='project',
            name='quinta_num',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='project',
            name='seccion',
            field=models.CharField(max_length=30, null=True, verbose_name='Seccion'),
        ),
        migrations.AddField(
            model_name='project',
            name='titular_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre y apellido'),
        ),
        migrations.AddField(
            model_name='project',
            name='titular_phone',
            field=models.IntegerField(default=0, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='project',
            name='tutlar_dni',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_dni',
            field=models.IntegerField(default=0, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_phone',
            field=models.IntegerField(default=0, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mens',
            field=models.CharField(choices=[('PH', 'PH'), ('Usucapion', 'Usucapion'), ('Division', 'Division'), ('Anexion/Division', 'Anexion/Division'), ('Unificacion', 'Unificacion')], max_length=30, null=True, verbose_name='Mensura'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Estado Parcelario', 'Estado Parcelario'), ('Mensura', 'Mensura'), ('Amojonamiento', 'Amojonamiento'), ('Relevamiento', 'Relevamiento'), ('Legajo Parcelario', 'Legajo Parcelario')], max_length=30, null=True, verbose_name='Proyecto'),
        ),
    ]
