# Generated by Django 4.2.4 on 2025-05-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfiles',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
