# Generated by Django 4.2.4 on 2025-04-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='adv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Anticipo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gasto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gastos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Presupuesto'),
        ),
    ]
