# Generated by Django 4.2.4 on 2025-05-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfiles',
            name='files',
        ),
        migrations.RemoveField(
            model_name='projectfiles',
            name='project',
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='project_pk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
