# Generated by Django 4.2.4 on 2025-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_projectfiles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='not_listed',
            field=models.BooleanField(default=False, verbose_name='No listado'),
        ),
    ]
