# Generated by Django 4.2.4 on 2025-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_alter_project_adv_alter_project_gasto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Fijo'),
        ),
    ]
