# Generated by Django 4.2.4 on 2025-04-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_remove_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', verbose_name='Tel'),
        ),
    ]
