# Generated by Django 4.2.4 on 2025-04-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_remove_project_manzana_letra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(verbose_name='Telefono'),
        ),
    ]
