# Generated by Django 4.2.4 on 2025-04-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(default='', verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titular_dni',
            field=models.CharField(verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titular_phone',
            field=models.CharField(verbose_name='Telefono'),
        ),
    ]
