# Generated by Django 4.2.4 on 2025-05-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_client_not_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Direccion'),
        ),
    ]
