# Generated by Django 4.2.4 on 2025-04-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(verbose_name='DNI'),
        ),
    ]
