# Generated by Django 4.2.3 on 2025-05-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_client_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_name',
            field=models.CharField(default='', max_length=30, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(default='', max_length=40, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titular_phone',
            field=models.CharField(default='', max_length=40, verbose_name='Telefono'),
        ),
    ]
