# Generated by Django 4.2.4 on 2023-08-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_alter_project_chacra_letra_alter_project_chacra_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='aprob',
        ),
    ]
