# Generated by Django 4.2.4 on 2025-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_alter_client_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(verbose_name='Tel'),
        ),
    ]
