# Generated by Django 4.2.4 on 2025-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_alter_client_dni_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(default='', max_length=40, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=40, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titular_dni',
            field=models.CharField(max_length=40, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titular_phone',
            field=models.CharField(max_length=40, verbose_name='Telefono'),
        ),
    ]
