# Generated by Django 4.2.4 on 2025-05-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_project_closed_alter_project_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='direction_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Calle'),
        ),
    ]
