# Generated by Django 4.2.3 on 2025-05-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_project_contact_name_project_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact_name',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='Telefono'),
        ),
    ]
