# Generated by Django 4.2.4 on 2023-08-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_remove_project_aprob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tutlar_dni',
            new_name='titular_dni',
        ),
    ]
