# Generated by Django 4.2.4 on 2025-05-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0005_project_direction_number_alter_project_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='msg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
