# Generated by Django 4.2.4 on 2023-11-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0005_rename_tutlar_dni_project_titular_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_dni',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='adv',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Anticipo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='chacra_letra',
            field=models.CharField(max_length=10, verbose_name='Letra'),
        ),
        migrations.AlterField(
            model_name='project',
            name='chacra_num',
            field=models.CharField(max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='project',
            name='circuns',
            field=models.CharField(max_length=30, verbose_name='Circunscripcion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.FileField(null=True, upload_to='media/files'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fraccion_letra',
            field=models.CharField(max_length=10, verbose_name='Letra'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fraccion_num',
            field=models.CharField(max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gasto',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Gastos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='inscription_type',
            field=models.CharField(choices=[('Folio', 'Folio'), ('Matricula', 'Matricula')], default=0, max_length=30, null=True, verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manzana_letra',
            field=models.CharField(max_length=10, verbose_name='Letra'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manzana_num',
            field=models.CharField(max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mens',
            field=models.CharField(choices=[('PH', 'PH'), ('Usucapion', 'Usucapion'), ('Division', 'Division'), ('Anexion/Division', 'Anexion/Division'), ('Unificacion', 'Unificacion')], max_length=30, verbose_name='Mensura'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parcela_letra',
            field=models.CharField(max_length=10, verbose_name='Letra'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parcela_num',
            field=models.CharField(max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partida',
            field=models.CharField(max_length=30, verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partido',
            field=models.CharField(max_length=30, verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='procedure',
            field=models.IntegerField(null=True, verbose_name='N° Tramite'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quinta_letra',
            field=models.CharField(max_length=10, verbose_name='Letra'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quinta_num',
            field=models.CharField(max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='project',
            name='seccion',
            field=models.CharField(max_length=30, verbose_name='Seccion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titular_dni',
            field=models.IntegerField(verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titular_name',
            field=models.CharField(max_length=30, verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titular_phone',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Estado Parcelario', 'Estado Parcelario'), ('Mensura', 'Mensura'), ('Amojonamiento', 'Amojonamiento'), ('Relevamiento', 'Relevamiento'), ('Legajo Parcelario', 'Legajo Parcelario')], max_length=30, verbose_name='Proyecto'),
        ),
    ]
