# Generated by Django 4.2.4 on 2025-04-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0005_alter_client_dni_alter_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='project',
            name='titular_dni',
        ),
    ]
