# Generated by Django 4.2.3 on 2025-06-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_alter_event_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='project',
            name='procedure',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Tramite'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titular_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titular_phone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Telefono'),
        ),
    ]
