# Generated by Django 4.2.4 on 2025-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_remove_client_dni_remove_project_titular_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='titular_name',
            field=models.CharField(default='', max_length=30, verbose_name='Nombre y apellido'),
        ),
    ]
