# Generated by Django 4.2.4 on 2023-11-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_remove_project_client_dni_remove_project_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('model_pk', models.IntegerField(default=0)),
                ('msg', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='titular_dni',
            field=models.IntegerField(verbose_name='DNI'),
        ),
    ]
