# Generated by Django 4.2.4 on 2023-11-09 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0007_event_alter_project_titular_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='adv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Anticipo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gasto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Gastos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Presupuesto'),
        ),
    ]
