# Generated by Django 4.2.4 on 2025-04-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0007_alter_project_titular_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='depto',
            field=models.CharField(blank=True, max_length=30, verbose_name='Depto'),
        ),
        migrations.AddField(
            model_name='project',
            name='direction',
            field=models.CharField(blank=True, max_length=30, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='project',
            name='floor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='project',
            name='parcela_letra',
            field=models.CharField(blank=True, max_length=10, verbose_name='Letra'),
        ),
        migrations.AddField(
            model_name='project',
            name='parcela_num',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='project',
            name='subparcela_letra',
            field=models.CharField(blank=True, max_length=10, verbose_name='Letra'),
        ),
        migrations.AddField(
            model_name='project',
            name='subparcela_num',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='project',
            name='inscription_type',
            field=models.CharField(choices=[('Folio', 'Folio'), ('Matricula', 'Matricula')], default='', max_length=30, null=True, verbose_name='Inscripcion'),
        ),
    ]
