# Generated by Django 4.2.4 on 2025-04-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0008_project_depto_project_direction_project_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subparcela_letra',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subparcela_num',
        ),
        migrations.AddField(
            model_name='project',
            name='subparcela',
            field=models.CharField(blank=True, max_length=10, verbose_name='Subparcela'),
        ),
    ]
