# Generated by Django 4.2.3 on 2025-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0008_alter_client_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paused',
            field=models.BooleanField(default=False, verbose_name='Pausado'),
        ),
    ]
