# Generated by Django 4.2.4 on 2023-11-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0008_project_created_project_updated_alter_project_adv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
        migrations.AlterField(
            model_name='project',
            name='inscription_type',
            field=models.CharField(choices=[('Folio', 'Folio'), ('Matricula', 'Matricula')], default='', max_length=30, null=True, verbose_name='Parcela'),
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='media/files')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project')),
            ],
        ),
    ]
