# Generated by Django 4.2.4 on 2025-04-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0009_remove_project_subparcela_letra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manzana_letra',
            field=models.CharField(blank=True, max_length=10, verbose_name='Letra'),
        ),
        migrations.AddField(
            model_name='project',
            name='manzana_num',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numero'),
        ),
    ]
