# Generated by Django 4.2.3 on 2025-08-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0009_project_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='direction_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Altura'),
        ),
    ]
