# Generated by Django 4.2.4 on 2023-11-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0010_rename_files_projectfiles_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfiles',
            old_name='file',
            new_name='files',
        ),
    ]
