# Generated by Django 4.2.4 on 2025-04-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0010_project_manzana_letra_project_manzana_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mens',
            field=models.CharField(blank=True, choices=[('PH', 'PH'), ('Usucapion', 'Usucapion'), ('Division', 'Division'), ('Anexion/Division', 'Anexion/Division'), ('Unificacion', 'Unificacion')], max_length=30, null=True, verbose_name='Mensura'),
        ),
    ]
