# Generated by Django 4.2.4 on 2025-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0011_alter_project_mens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='depto',
            field=models.CharField(blank=True, max_length=10, verbose_name='Depto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.CharField(blank=True, max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='floor',
            field=models.CharField(blank=True, max_length=10, verbose_name='Piso'),
        ),
    ]
