# Generated by Django 4.2.3 on 2025-11-28 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ProjectManager", "0012_client_created_by_event_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_group_project",
            field=models.BooleanField(
                default=False,
                help_text="Indica si este proyecto es colaborativo entre varios usuarios",
                verbose_name="Proyecto Grupal",
            ),
        ),
        migrations.CreateModel(
            name="ProjectCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Porcentaje de las ganancias netas que corresponde a este usuario",
                        max_digits=5,
                        verbose_name="Porcentaje de Ganancias",
                    ),
                ),
                (
                    "added_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Agregado"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="ProjectManager.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborated_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador de Proyecto",
                "verbose_name_plural": "Colaboradores de Proyectos",
                "ordering": ["-percentage"],
                "unique_together": {("project", "user")},
            },
        ),
    ]
