# Generated by Django 4.2.3 on 2025-06-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectManager', '0006_alter_event_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('netWorth', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ProjectManager.project')),
            ],
            options={
                'verbose_name': 'Cobranza',
                'verbose_name_plural': 'Cobranzas',
            },
        ),
        migrations.CreateModel(
            name='AccountMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('movement_type', models.CharField(choices=[('ADV', 'Anticipo'), ('EXP', 'Gasto')], max_length=3, verbose_name='Tipo de Movimiento')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='Accounting.account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project', verbose_name='Proyecto')),
            ],
        ),
    ]
