# Generated by Django 4.2.3 on 2025-06-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_alter_event_msg'),
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='account',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project'),
        ),
    ]
