# Generated by Django 4.2.3 on 2025-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_account_created_alter_account_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='estimaded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='accountmovement',
            name='movement_type',
            field=models.CharField(choices=[('ADV', 'Anticipo'), ('EXP', 'Gasto'), ('EST', 'Presupuesto')], max_length=3, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AddIndex(
            model_name='accountmovement',
            index=models.Index(fields=['account', 'created_at'], name='Accounting__account_9cfbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmovement',
            index=models.Index(fields=['movement_type'], name='Accounting__movemen_cb2bb0_idx'),
        ),
    ]
