# Generated by Django 4.2.3 on 2025-06-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0003_account_estimaded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='estimaded',
            new_name='estimated',
        ),
    ]
