# Generated by Django 4.2.3 on 2025-06-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0004_rename_estimaded_account_estimated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('total_estimated', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Presupuesto Total')),
                ('total_advance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Cobros Total')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Gastos Total')),
                ('total_networth', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ganancia Neta')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Resumen Mensual',
                'verbose_name_plural': 'Resumenes Mensuales',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='Accounting__year_183f9e_idx')],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
