# Generated by Django 4.2.3 on 2025-06-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0005_monthlyfinancialsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyfinancialsummary',
            name='total_estimated',
        ),
    ]
