# Generated by Django 4.2.3 on 2025-06-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0006_remove_monthlyfinancialsummary_total_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfinancialsummary',
            name='total_net_amoj',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ganancia Neta Amojonamiento'),
        ),
        migrations.AddField(
            model_name='monthlyfinancialsummary',
            name='total_net_est_parc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ganancia Neta Est Parcelario'),
        ),
        migrations.AddField(
            model_name='monthlyfinancialsummary',
            name='total_net_leg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ganancia Neta Legajos'),
        ),
        migrations.AddField(
            model_name='monthlyfinancialsummary',
            name='total_net_mensura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ganancia Neta Mensura'),
        ),
        migrations.AddField(
            model_name='monthlyfinancialsummary',
            name='total_net_relev',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ganancia Neta Relevamiento'),
        ),
    ]
