# Generated by Django 4.2.3 on 2025-07-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0007_monthlyfinancialsummary_total_net_amoj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmovement',
            options={'verbose_name': 'Movimiento de Cuenta', 'verbose_name_plural': 'Movimientos de Cuenta'},
        ),
    ]
