# Generated by Django 5.2.3 on 2025-08-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0008_alter_accountmovement_options'),
        ('ProjectManager', '0010_alter_project_direction_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimiento de Cuenta', 'verbose_name_plural': 'Movimientos de Cuenta'},
        ),
        migrations.AddIndex(
            model_name='accountmovement',
            index=models.Index(fields=['project', 'created_at'], name='Accounting__project_39944d_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmovement',
            index=models.Index(fields=['-created_at', 'movement_type'], name='Accounting__created_5ce2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmovement',
            index=models.Index(fields=['created_at'], name='Accounting__created_c45b55_idx'),
        ),
    ]
