# Generated by Django 4.2.3 on 2025-11-25 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounting', '0009_alter_accountmovement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfinancialsummary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
