# Generated by Django 4.2.3 on 2025-11-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ProjectManager", "0012_client_created_by_event_created_by"),
        ("Accounting", "0010_monthlyfinancialsummary_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="ProjectManager.project",
            ),
        ),
    ]
